### ISSUE TITLE
Python file `opt_so_comb_set_covering_problem_ilp.py` should execute correctly

### ISSUE THREAD

**Issue by vladofilipovic** [vladofilipovic/universal-optimizer#112]
Execution of the pyhon file produced following error:

```
<class 'int'>
Sebset element:  349
<class 'int'>
Traceback (most recent call last):
  File "c:\vlado\Science\Prog\optimization\----universal-optimizer\opt_so_comb_set_covering_problem_ilp.py", line 50, in <module>
    main()
  File "c:\vlado\Science\Prog\optimization\----universal-optimizer\opt_so_comb_set_covering_problem_ilp.py", line 45, in main
    bs = solver.optimize()
         ^^^^^^^^^^^^^^^^^
  File "c:\vlado\Science\Prog\optimization\----universal-optimizer\opt\single_objective\comb\set_covering_problem\set_covering_problem_ilp_linopy.py", line 171, in optimize
    linear_expr = LinearExpression.dot(x, transposed_vector)
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'LinearExpression' has no attribute 'dot'
```

**Comment by vladofilipovic** [comment]
If you use another, novel version of the `linopy` poetry hould be changed.

Please, create a branch, solve the issue, and then create the pull request, so patch will be merged into solution
