### ISSUE TITLE
Two unit tests within `test_set_covering_problem.py` does not working

### ISSUE THREAD

**Issue by vladofilipovic** [vladofilipovic/universal-optimizer#113]
All unit unit tests within file `test_set_covering_problem.py` should work

**Comment by vladofilipovic** [comment]
![Image](https://github.com/user-attachments/assets/0f328f99-350f-425d-ad46-0e66e89fb801)

**Comment by vladofilipovic** [comment]
![Image](https://github.com/user-attachments/assets/f8330ecf-5c33-4782-9cfc-77c79ea2b9ef)

**Comment by vladofilipovic** [comment]
Output of the first test that does not work:
```
opt.tests.unit.single_objective.comb.set_covering_problem.test_set_covering_problem.TestSetCoveringProblem.test_string_representation_includes_universe_and_subset_property failed: <class 'AssertionError'> 'subsets=[{1, 2, 3}, {3, 4}, {3, 4, 5}, {1, 5}, {4}]' not found in '|{||name=SetCoveringProblem|is_minimization=True|universe ={1, 2, 3, 4, 5, 6}|subsets =[{1, 2, 3}, {3, 4}, {3, 4, 5}, {1, 5}, {4}]|}'
Traceback (most recent call last):
  File "C:\Python311\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Python311\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\Python311\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "c:\vlado\Science\Prog\optimization\----universal-optimizer\opt\tests\unit\single_objective\comb\set_covering_problem\test_set_covering_problem.py", line 41, in test_string_representation_includes_universe_and_subset_property
    self.assertIn('subsets=' + str(subsets), string_rep)
AssertionError: 'subsets=[{1, 2, 3}, {3, 4}, {3, 4, 5}, {1, 5}, {4}]' not found in '|{||name=SetCoveringProblem|is_minimization=True|universe ={1, 2, 3, 4, 5, 6}|subsets =[{1, 2, 3}, {3, 4}, {3, 4, 5}, {1, 5}, {4}]|}'
```

**Comment by vladofilipovic** [comment]
Output of the second test that does not work:

```
opt.tests.unit.single_objective.comb.set_covering_problem.test_set_covering_problem.TestSetCoveringProblem.test_instantiation_from_input_file failed with error: <class 'AttributeError'> <class 'opt.single_objective.comb.set_covering_problem.set_covering_problem.SetCoveringProblem'> does not have the attribute '__load_from_file__'
Traceback (most recent call last):
  File "C:\Python311\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Python311\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "C:\Python311\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "c:\vlado\Science\Prog\optimization\----universal-optimizer\opt\tests\unit\single_objective\comb\set_covering_problem\test_set_covering_problem.py", line 66, in test_instantiation_from_input_file
    with mocker.patch.object(SetCoveringProblem, '__load_from_file__', side_effect=ValueError):
  File "C:\Python311\Lib\unittest\mock.py", line 1437, in __enter__
    original, local = self.get_original()
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\unittest\mock.py", line 1410, in get_original
    raise AttributeError(
AttributeError: <class 'opt.single_objective.comb.set_covering_problem.set_covering_problem.SetCoveringProblem'> does not have the attribute '__load_from_file__'
```
